[rojak-pantau][WIP] feat: JawaPos spider
pyk/rojak pull request #101
Opened 2016-10-16 10:03 UTC by rilut

Work in progress, mohon jangan di-merge terlebih dahulu :smile:

Fixes: #39 
Blocked by: #100

2016-10-17 04:52 UTC, rilut commented
(belum benar. masih salah masukin ke loader)

2016-10-18 01:50 UTC, pyk commented
@rilut untuk jawapos yang kasus multi-page banyak gak mas? kalo dikit, kita skip dulu aja gimana mas? Kita handle yg one-page dulu (tapi make sure yg multi-page kita skip, biar gak ada invalid `raw_content`)

2016-10-26 18:03 UTC, pyk commented
@rilut untuk handle multi-page bisa lihat teknik yang di pakai @rawgni di https://github.com/pyk/rojak/blob/c6ff60a4f8edd1b6d47081683d7f2945d0fb2a89/rojak-pantau/rojak_pantau/spiders/detikcom.py#L99-L100

```
yield Request(index, meta={'loader': loader, 'n': len(indices)},
                    callback=self.parse_multipage_content)
```

dia yield request dari `loader` yg sebelumnya, jadi datanya bisa di append.

2016-10-27 12:33 UTC, rilut commented
@pyk siap!

2016-10-27 14:29 UTC, rilut commented
Terima kasih mas @pyk, dan terutama mas @rawgni

2016-10-28 13:37 UTC, pyk requested changes
Cuman yg data title mungkin kelupaan gak di handle fail-safe nya, secara keseluruhan udah Ok 👌

2016-10-28 13:37 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/jawapos.py
> +        title = response.css('h1.detailtitle::text').extract_first().strip()
btw ini kita harus pake fail-safe, kita asumsikan kalau `title` belum tentu ada dan kalo gak ada kita drop itemnya. Biar data yg kita pantau valid.

Contohnya seperti ini https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L111-L116

2016-10-29 02:33 UTC, pyk approved these changes

2016-10-29 02:34 UTC, merged