[rojak-pantau] Hotfix/rojak pantau/metrotvnews failsafe
pyk/rojak pull request #104
Opened 2016-10-17 00:44 UTC by girikuncoro

Merge for #79

2016-10-18 02:14 UTC, pyk requested changes
LGTM 👌 , tinggal masalah noise di `raw_content` diatas mas https://github.com/pyk/rojak/pull/104#discussion_r83771025

2016-10-18 02:14 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
Untuk selector ini kita masih dapet `iframe` terus list judul related article nya mas.

```
>>> response.css('div.part.article').extract()
[u'<div class="part article">\r\n        <p><strong>Metrotvnews.com, Jakarta: </strong>Badan Nasional Narkotika (BNN) mewaspadai adanya duit bandar narkoba yang masuk ke rekening pasangan bakal calon kepala daerah untuk biaya Pilkada Serentak 2017.<br>\r\n\xa0<br>\r\nKepala BNN Komjen Budi Waseso mengatakan, pihaknya akan bekerja sama dengan Pusat Pelaporan dan Analisis Transaksi Keuangan (PPATK) dan Komisi Pemilihan Umum (KPU) untuk menyelidiki adanya dana hasil bisnis narkotika bari bandar narkoba yang masuk untuk membiayai kampanye calon kepala daerah.<br>\r\n\xa0<br>\r\nBudi Waseso mengaku telah mengirim sejumlah data transaksi yang dicurigai terkait sindikat narkotika. Dia berharap PPATK menindaklanjuti data itu dengan melakukan penyelidikan apakah ada calon kepala daerah yang memiliki hubungan dengan bandar narkotika.<br>\r\n\xa0<br>\r\n\u201cPrinsipnya BNN kerja sama dengan Polri, Bea Cukai, PPATK, untuk kita sinergi dalam rangka pengungkapan atau penegakan hukum terhadap narkotika yang terus beroperasi di wilayah kita," kata Budi Waseso di Kantor BNN, Cawang, Jakarta Timur, Kamis (13/10/2016).<br><br>\r\n
<iframe class="embedv" width="560" height="315" src="http://www.metrotvnews.com/embed/aNrLjq2k" frameborder="0" scrolling="no" allowfullscreen></iframe>\r\n                

</p><ul class="part related">\r\n                    <li>\r\n                      <div class="ti4"> Baca Juga : </div>\r\n                    </li>\r\n            \r\n                    <li>\r\n                       <div class="fl n">\r\n                            
<h2 class="title">\r\n                            <a title="PPP Kubu Djan Faridz Resmi Dukung Ahok-Djarot" href="http://m.metrotvnews.com/welcome-page/photo/zNAG0A2k-ppp-kubu-djan-faridz-resmi-dukung-ahok-djarot">PPP Kubu Djan Faridz Resmi Dukung Ahok-Djarot</a>\r\n                        </h2>\r\n                       </div>    \r\n                    </li>\r\n                \r\n                    <li>\r\n                       <div class="fl n">\r\n                            
<h2 class="title">\r\n                            <a title="Demokrat Sambut Baik Dukungan Lulung ke Agus-Sylvi" href="http://m.metrotvnews.com/news/politik/8koXGMYK-demokrat-sambut-baik-dukungan-lulung-ke-agus-sylvi">Demokrat Sambut Baik Dukungan Lulung ke Agus-Sylvi</a>\r\n                        </h2>\r\n                       </div>    \r\n                    </li>\r\n                \r\n                    <li>\r\n                       <div class="fl n">\r\n                            <h2 class="title">\r\n                            <a title="Daftar Program Konkret yang Disodorkan PPP Djan Faridz ke Ahok" href="http://m.metrotvnews.com/news/politik/eN47EqOK-daftar-program-konkret-yang-disodorkan-ppp-djan-faridz-ke-ahok">Daftar Program Konkret yang Disodorkan PPP Djan Faridz ke Ahok</a>\r\n                        </h2>\r\n                       </div>    \r\n                    </li>\r\n                \r\n                    <li>\r\n                       <div class="fl n">\r\n                            <h2 class="title">\r\n                            <a href="http://www.metrotvnews.com/brandconnect" class="bc-link">Brandconnect</a>\r\n                            <a title="SCG Berkomitmen Bangun Indonesia Jadi Lebih Baik" href="http://m.metrotvnews.com/news/peristiwa/1bVXnBQK-scg-berkomitmen-bangun-indonesia-jadi-lebih-baik">SCG Berkomitmen Bangun Indonesia Jadi Lebih Baik</a>\r\n                        </h2>\r\n                      
 </div>    \r\n                    </li>\r\n                </ul>\r\nBudi Berharap, para calon kepala daerah bersikap terbuka dengan memberikan data harta kekayaannya dan sumber dana yang akan digunakan untuk Pilkada. "Karena tidak menutup kemungkinan hasil bisnis narkoba untuk kegiatan pembiayaan pilkada," katanya.<br>\r\n\xa0<br>\r\nBakal calon Gubernur DKI Jakarta Basuki Tjahaja Purnama alias Ahok menegaskan kampanye tanpa uang. Dia menuturkan tiga partai pendukungnya berjanji mengeluarkan dana kampanye.<br>\r\n\xa0<br>\r\nMeski dijanjikan, Ahok mengaku tak tahu berapa jumlah pasti dana yang akan diberikan NasDem, Hanura dan Golkar. Mantan bupati Belitung Timur ini juga kerap membeberkan tak diperkenankan merogoh kocek dalam pertemuan apapun dengan partai.<br>\r\n\xa0<br>\r\n"Ketemu di mana mereka yang bayarin semua. Artinya di mata mereka saya enggak ada duit. Bagus dong," ucap Ahok.<br>\r\n\xa0<br>\r\nKarena tak ingin merogoh kocek, Ahok pun mulai membentuk strategi mengumpulkan dana. Berkali-kali disampaikan keinginannya untuk menarik dana dari pendukungnya sendiri. Beberapa caranya, adalah menyebarkan pesan singkat sumbangan minimal Rp50 ribu per kepala.<br>\r\n\xa0<br>\r\nKemudian, Ahok berminat kembali mengadakan Teman Ahok fair yang nantinya para penonton bakal dikenakan biaya. Terakhir Ahok berniat membuat acara makan malam yang nantinya juga akan dikenakan tarif per kepala.<br>\r\n\xa0<br>\r\n"Kalau dulu orang berikan KTP dan orangnya pasti minta harga untuk satu KTP. Sekarang saya balikin," ucap Ahok.<br><br>\r\n<iframe class="embedv" width="560" height="315" src="http://www.metrotvnews.com/embed/ybD153pk" frameborder="0" scrolling="no" allowfullscreen></iframe><br><br>\r\n\r\n        <br>(FZN)\r\n\t\t        \r\n    </div>']
```

Dimana itu akan jadi noise ketika analisa sentiment nya.

Kita bisa pake `xpath` ini mas:

```python
xpath_query = '''
//div[@class="part article"]/node()
    [not(
        descendant-or-self::comment()|
        descendant-or-self::script|
        descendant-or-self::div|
        descendant-or-self::iframe)]
'''
raw_content = response.xpath(xpath_query)
raw_content = ' '.join(raw_content).strip()
```

Kita dapet xpath yang bersih dari noise diatas
```
>> response.xpath(xpath_query).extract()
[u'\r\n        ', u'\r\nBudi Berharap, para calon kepala daerah bersikap terbuka dengan memberikan data harta kekayaannya dan sumber dana yang akan digunakan untuk Pilkada. "Karena tidak menutup kemungkinan hasil bisnis narkoba untuk kegiatan pembiayaan pilkada," katanya.', u'<br>', u'\r\n\xa0', u'<br>', u'\r\nBakal calon Gubernur DKI Jakarta Basuki Tjahaja Purnama alias Ahok menegaskan kampanye tanpa uang. Dia menuturkan tiga partai pendukungnya berjanji mengeluarkan dana kampanye.', u'<br>', u'\r\n\xa0', u'<br>', u'\r\nMeski dijanjikan, Ahok mengaku tak tahu berapa jumlah pasti dana yang akan diberikan NasDem, Hanura dan Golkar. Mantan bupati Belitung Timur ini juga kerap membeberkan tak diperkenankan merogoh kocek dalam pertemuan apapun dengan partai.', u'<br>', u'\r\n\xa0', u'<br>', u'\r\n"Ketemu di mana mereka yang bayarin semua. Artinya di mata mereka saya enggak ada duit. Bagus dong," ucap Ahok.', u'<br>', u'\r\n\xa0', u'<br>', u'\r\nKarena tak ingin merogoh kocek, Ahok pun mulai membentuk strategi mengumpulkan dana. Berkali-kali disampaikan keinginannya untuk menarik dana dari pendukungnya sendiri. Beberapa caranya, adalah menyebarkan pesan singkat sumbangan minimal Rp50 ribu per kepala.', u'<br>', u'\r\n\xa0', u'<br>', u'\r\nKemudian, Ahok berminat kembali mengadakan Teman Ahok fair yang nantinya para penonton bakal dikenakan biaya. Terakhir Ahok berniat membuat acara makan malam yang nantinya juga akan dikenakan tarif per kepala.', u'<br>', u'\r\n\xa0', u'<br>', u'\r\n"Kalau dulu orang berikan KTP dan orangnya pasti minta harga untuk satu KTP. Sekarang saya balikin," ucap Ahok.', u'<br>', u'<br>', u'\r\n', u'<br>', u'<br>', u'\r\n\r\n        ', u'<br>', u'(FZN)\r\n\t\t        \r\n    ']
```

2016-10-18 02:21 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
eh ternyata waktu exclude iframe, `p` juga hilang. Jadi paragraph pertama juga hilang hmmmmm. 

Enaknya gimana ya mas?
Apa kita query satu2 terus gabung?

2016-10-18 16:33 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
oke ntar malem tak maenkan dulu ya

2016-10-19 01:29 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
@girikuncoro aku kemaren kepikiran pake BeautifulSoup aja sih mas. Jadi waktu dapet raw_content itu tinggal masukkan ke beautifulsoup lalu kita remove noise element seperti list related judul berita dan iframe

2016-10-19 01:35 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
hmm sbenernya ga ilang kok, cuma emang paragraf pertama di tag `p` yang beda, ini hasilnya:

`$x('//div[@class="part article"]')`
```
<div class="part article">
        <p><strong>Metrotvnews.com, Jakarta</strong>: Komisi Pemilihan Umum (KPU) DKI Jakarta membatasi penggunaan dana kampanye pada Pilgub DKI 2017. Sumber dana pasangan calon hanya boleh datang dari pasangan calon, partai, dan pihak lain yang sah menurut hukum.<br><br>
Komisioner KPU DKI Jakarta Bidang Pencalonan dan Kampanye Dahlia Umar menjelaskan, pembatasan dana kampanye terdiri dari pembatasan pemasukan dan pembatasan pengeluaran. Sumber dana bisa berbentuk uang, barang, dan jasa.
                </p><ul class="part related">
                    <li>
                      <div class="ti4"> Baca Juga : </div>
                    </li>
            
                    <li>
                       <div class="fl n">
                            <h2 class="title">
                            <a title="Teman Ahok Wajib Kembalikan Duit Kelebihan Untung Penjualan <i>Merchandise</i> Ahok" href="http://m.metrotvnews.com/news/metro/DkqjYwZK-teman-ahok-wajib-kembalikan-duit-kelebihan-untung-penjualan-merchandise-ahok">Teman Ahok Wajib Kembalikan Duit Kelebihan Untung Penjualan <i>Merchandise</i> Ahok</a>
                        </h2>
                       </div>    
                    </li>
                
                    <li>
                       <div class="fl n">
                            <h2 class="title">
                            <a title="Timses Cagub DKI Wajib Daftarkan Akun Medsos Kampanye" href="http://m.metrotvnews.com/video/headline-news/VNxJGLxk-timses-cagub-dki-wajib-daftarkan-akun-medsos-kampanye">Timses Cagub DKI Wajib Daftarkan Akun Medsos Kampanye</a>
                        </h2>
                       </div>    
                    </li>
                
                    <li>
                       <div class="fl n">
                            <h2 class="title">
                            <a title="Setiap Cagub-Cawagub DKI Bakal Dikawal 30 Polisi" href="http://m.metrotvnews.com/news/metro/zNPA6aXb-setiap-cagub-cawagub-dki-bakal-dikawal-30-polisi">Setiap Cagub-Cawagub DKI Bakal Dikawal 30 Polisi</a>
                        </h2>
                       </div>    
                    </li>
                
                    <li>
                       <div class="fl n">
                            <h2 class="title">
                            <a href="http://www.metrotvnews.com/brandconnect" class="bc-link">Brandconnect</a>
                            <a title="SCG Berkomitmen Bangun Indonesia Jadi Lebih Baik" href="http://m.metrotvnews.com/news/peristiwa/1bVXnBQK-scg-berkomitmen-bangun-indonesia-jadi-lebih-baik">SCG Berkomitmen Bangun Indonesia Jadi Lebih Baik</a>
                        </h2>
                       </div>    
                    </li>
                </ul>
Sumber dana kampanye yang berasal dari perseorangan tidak boleh melebihi Rp75 juta. Kelompok dan atau badan hukum swasta paling banyak Rp750 juta. Sumbangan dari parpol maksimal Rp750 juta. Hanya sumber dana dari paslon yang tidak dibatasi jumlahnya.<br><br>
"Di undang-undang, yang dibatasi bukan maksimal penerimaan sumbangan, tapi maksimal yang disumbangkan oleh penyumbang," jelas Dahlia dalam acara sosialisasi kampanye dan dana kampanye Pilgub DKI 2017 di Hotel Mercure, Jalan Cikini Raya, Jakarta Pusat, Selasa (18/10/2016).<br><br>
Pembatasan pengeluaran dana kampanye adalah akumulasi dari empat kegiatan. Pertama, pengeluaran rapat umum, yakni jumlah peserta dikali frekuensi kegiatan dikali standar biaya daerah.<br><br>
Kedua, pengeluaran pertemuan terbatas, yakni jumlah peserta dikali frekuensi kegiatan dikali standar biaya daerah.<br><br>
Ketiga, pertemuan tatap muka, yakni jumlah peserta dikali frekuensi dikali standar biaya daerah. Pembuatan bahan kampanye dengan perhitungan jumlah kegiatan dikali (30% dikali jumlah pemilih) dikali Rp25.000.<br><br>
Alat peraga kampanye yang dibiayai paslon jumlahnya berpedoman pada Keputusan KPU Provinsi/KIP Aceh atau KPU/KIP Kabupaten. "Jadi, secara otomatis sumbangan berapa pun yang diterima calon pada akhirnya akan dibatasi pengeluarannya," imbuh dia.<br><br>
KPU DKI tidak mengatur mekanisme jika terjadi kelebihan dana kampanye. Komisioner KPU DKI Bidang Sosialisasi Betty Idroos mengatakan, pihaknya akan berkoordinasi terkait kelebihan dana kampanye dengan KPU RI.<br><br>
"Itu ada kekosongan (hukum), tidak diatur, dan sepanjang pengetahuan saya, sudah berkoordinasi dengan KPU RI sisa itu belum tahu akan dikemanain, apakah dikembakikan kepada kas negara atau dapat dikelola oleh tim setelah terpilih," kata Betty.<br><br>
<iframe allowfullscreen="" class="embedv" frameborder="0" height="315" scrolling="no" src="http://www.metrotvnews.com/embed/aNrLOv6k" width="560"></iframe> &nbsp;<br><br>

        <br>(MBM)<p></p>
		        
    </div>
```

dari http://m.metrotvnews.com/pilkada/news-pilkada/1bVYDO2N-kpu-dki-batasi-dana-kampanye

coba bandingin deh, gimana?

2016-10-19 01:36 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
wait ada typo

2016-10-19 01:42 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
`$x('//div[@class="part article"]/node()
  [not(
    descendant-or-self::comment()|
    descendant-or-self::script|
    descendant-or-self::div|
    descendant-or-self::iframe)]')`

```
[u'\r\n        ',
 u'<p><strong>Metrotvnews.com, Jakarta</strong>: Komisi Pemilihan Umum (KPU) DKI Jakarta membatasi penggunaan dana kampanye pada Pilgub DKI 2017. Sumber dana pasangan calon hanya boleh datang dari pasangan calon, partai, dan pihak lain yang sah menurut hukum.<br><br>\r\nKomisioner KPU DKI Jakarta Bidang Pencalonan dan Kampanye Dahlia Umar menjelaskan, pembatasan dana kampanye terdiri dari pembatasan pemasukan dan pembatasan pengeluaran. Sumber dana bisa berbentuk uang, barang, dan jasa.\r\n                </p>',
 u'\r\nSumber dana kampanye yang berasal dari perseorangan tidak boleh melebihi Rp75 juta. Kelompok dan atau badan hukum swasta paling banyak Rp750 juta. Sumbangan dari parpol maksimal Rp750 juta. Hanya sumber dana dari paslon yang tidak dibatasi jumlahnya.',
 u'<br>',
 u'<br>',
 u'\r\n"Di undang-undang, yang dibatasi bukan maksimal penerimaan sumbangan, tapi maksimal yang disumbangkan oleh penyumbang," jelas Dahlia dalam acara sosialisasi kampanye dan dana kampanye Pilgub DKI 2017 di Hotel Mercure, Jalan Cikini Raya, Jakarta Pusat, Selasa (18/10/2016).',
 u'<br>',
 u'<br>',
 u'\r\nPembatasan pengeluaran dana kampanye adalah akumulasi dari empat kegiatan. Pertama, pengeluaran rapat umum, yakni jumlah peserta dikali frekuensi kegiatan dikali standar biaya daerah.',
 u'<br>',
 u'<br>',
 u'\r\nKedua, pengeluaran pertemuan terbatas, yakni jumlah peserta dikali frekuensi kegiatan dikali standar biaya daerah.',
 u'<br>',
 u'<br>',
 u'\r\nKetiga, pertemuan tatap muka, yakni jumlah peserta dikali frekuensi dikali standar biaya daerah. Pembuatan bahan kampanye dengan perhitungan jumlah kegiatan dikali (30% dikali jumlah pemilih) dikali Rp25.000.',
 u'<br>',
 u'<br>',
 u'\r\nAlat peraga kampanye yang dibiayai paslon jumlahnya berpedoman pada Keputusan KPU Provinsi/KIP Aceh atau KPU/KIP Kabupaten. "Jadi, secara otomatis sumbangan berapa pun yang diterima calon pada akhirnya akan dibatasi pengeluarannya," imbuh dia.',
 u'<br>',
 u'<br>',
 u'\r\nKPU DKI tidak mengatur mekanisme jika terjadi kelebihan dana kampanye. Komisioner KPU DKI Bidang Sosialisasi Betty Idroos mengatakan, pihaknya akan berkoordinasi terkait kelebihan dana kampanye dengan KPU RI.',
 u'<br>',
 u'<br>',
 u'\r\n"Itu ada kekosongan (hukum), tidak diatur, dan sepanjang pengetahuan saya, sudah berkoordinasi dengan KPU RI sisa itu belum tahu akan dikemanain, apakah dikembakikan kepada kas negara atau dapat dikelola oleh tim setelah terpilih," kata Betty.',
 u'<br>',
 u'<br>',
 u'\r\n',
 u' \xa0',
 u'<br>',
 u'<br>',
 u'\r\n\r\n        ',
 u'<br>',
 u'(MBM)\r\n\t\t        \r\n    ']
```

itu paragraf pertama emang di tag `p` yang terpisah gitu, coba cek lagi. ini hasil di atas diambil dari: http://m.metrotvnews.com/pilkada/news-pilkada/1bVYDO2N-kpu-dki-batasi-dana-kampanye

gimana?

2016-10-19 01:45 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
Woah mantap mas 👍

2016-10-19 01:46 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/metrotvnews.py
> +        raw_content_selectors = response.css('div.part.article')
```
In [5]: ' '.join(raw_content.extract())
Out[5]: u'\r\n         <p><strong>Metrotvnews.com, Jakarta</strong>: Komisi Pemilihan Umum (KPU) DKI Jakarta membatasi penggunaan dana kampanye pada Pilgub DKI 2017. Sumber dana pasangan calon hanya boleh datang dari pasangan calon, partai, dan pihak lain yang sah menurut hukum.<br><br>\r\nKomisioner KPU DKI Jakarta Bidang Pencalonan dan Kampanye Dahlia Umar menjelaskan, pembatasan dana kampanye terdiri dari pembatasan pemasukan dan pembatasan pengeluaran. Sumber dana bisa berbentuk uang, barang, dan jasa.\r\n                </p> \r\nSumber dana kampanye yang berasal dari perseorangan tidak boleh melebihi Rp75 juta. Kelompok dan atau badan hukum swasta paling banyak Rp750 juta. Sumbangan dari parpol maksimal Rp750 juta. Hanya sumber dana dari paslon yang tidak dibatasi jumlahnya. <br> <br> \r\n"Di undang-undang, yang dibatasi bukan maksimal penerimaan sumbangan, tapi maksimal yang disumbangkan oleh penyumbang," jelas Dahlia dalam acara sosialisasi kampanye dan dana kampanye Pilgub DKI 2017 di Hotel Mercure, Jalan Cikini Raya, Jakarta Pusat, Selasa (18/10/2016). <br> <br> \r\nPembatasan pengeluaran dana kampanye adalah akumulasi dari empat kegiatan. Pertama, pengeluaran rapat umum, yakni jumlah peserta dikali frekuensi kegiatan dikali standar biaya daerah. <br> <br> \r\nKedua, pengeluaran pertemuan terbatas, yakni jumlah peserta dikali frekuensi kegiatan dikali standar biaya daerah. <br> <br> \r\nKetiga, pertemuan tatap muka, yakni jumlah peserta dikali frekuensi dikali standar biaya daerah. Pembuatan bahan kampanye dengan perhitungan jumlah kegiatan dikali (30% dikali jumlah pemilih) dikali Rp25.000. <br> <br> \r\nAlat peraga kampanye yang dibiayai paslon jumlahnya berpedoman pada Keputusan KPU Provinsi/KIP Aceh atau KPU/KIP Kabupaten. "Jadi, secara otomatis sumbangan berapa pun yang diterima calon pada akhirnya akan dibatasi pengeluarannya," imbuh dia. <br> <br> \r\nKPU DKI tidak mengatur mekanisme jika terjadi kelebihan dana kampanye. Komisioner KPU DKI Bidang Sosialisasi Betty Idroos mengatakan, pihaknya akan berkoordinasi terkait kelebihan dana kampanye dengan KPU RI. <br> <br> \r\n"Itu ada kekosongan (hukum), tidak diatur, dan sepanjang pengetahuan saya, sudah berkoordinasi dengan KPU RI sisa itu belum tahu akan dikemanain, apakah dikembakikan kepada kas negara atau dapat dikelola oleh tim setelah terpilih," kata Betty. <br> <br> \r\n  \xa0 <br> <br> \r\n\r\n         <br> (MBM)\r\n\t\t        \r\n    '
```

2016-10-19 02:00 UTC, pyk approved these changes

2016-10-19 02:00 UTC, merged