Completed tempo.co spider #39
pyk/rojak pull request #121
Opened 2016-10-22 15:24 UTC by kevinluvian

merge for #39

kemarin yang aku maksud rekursif begini @pyk , kalo for loop gmn yah?
maaf kalo codenya agak berantakan, aku buatnya agak buru2 barusan :sweat_smile:

2016-10-22 15:53 UTC, kevinluvian commented
oh ya,
untuk author_name, news ini agak ga konsisten. sepertinya mereka masukin author name itu manual di news_content, bukan sebagai attribute khusus.
tau dari mana? dari response apinya mereka sih begini
```
{
	"code": 200,
	"status": "success.",
	"result": {
		"isAds": 0,
		"newsId": "813969",
		"title": "Aliansi Mahasiswa Sampaikan Manifesto 2 Tahun Jokowi-JK",
		"content": "<p><span style=\"color: #666666;\"><strong>TEMPO.CO<\/strong><\/span>, <span style=\"color: #666666;\"><strong>Jakarta<\/strong><\/span> - Aliansi Mahasiswa Indonesia menyampaikan manifesto terkait 2 tahun pemerintahan Jokowi-JK. Manifesto Aliansi Mahasiswa Indonesia tersebut merupakan hasil simposium mengevaluasi 2 tahun Pemerintahan Jokowi-Jk yang dilaksanakan pada Rabu, 19 Oktober 2016 di Margasiswa PMKRI, Jl. Sam Ratulangie, Nomor 1. Menteng, Jakarta. <br \/><br \/>Manifesto dibacakan oleh Ketua Pengurus Besar PMII Aminudin Ma'Ruf didampingi Ketua HMI Mulyadi P Tamsir dan Ketua PP PMKRI Angelo Wake Kako. Berikut isi Manifesto Aliansi Mahasiswa Indonesia yang disampaikan di depan Istana Negara. <br \/><br \/>1. Mendorong pembangunan nasional yang merata dengan memperhatikan daerah terpencil dan terdepan serta mengutamakan pendayagunaan sumber daya dalam negeri.<br \/><br \/>2. Mendesak pengembangan industri pangan strategis demi terwujudnya kedaulatan&nbsp; pangan di Indonesia. Mendorong penguatan industri dalam negeri yang berorientasi nilai tambah di segala sektor. Reformasi BUMN agar menjadi pendorong utama pembangunan ekonomi nasional.<br \/><br \/>3. Wujudkan kemandirian energi, mengembangkan energi terbarukan, dan hentikan ekspor bahan material mentah dari bumi Indonesia. Hentikan proyek reklamasi yang mengganggu keseimbangan ekologi dan sosial.<br \/><br \/>Baca: <br \/><a title=\"Ahok Puji Jokowi, Berharap Terpilih Lagi di Pilpres 2019\" href=\"https:\/\/nasional.tempo.co\/read\/news\/2016\/10\/20\/078813852\/ahok-puji-jokowi-berharap-terpilih-lagi-di-pilpres-2019\">Ahok Puji Jokowi, Berharap Terpilih Lagi di Pilpres 2019<br \/><\/a><a title=\"Media Terseret Dugaan Penyuapan, Ini Kata AJI\" href=\"https:\/\/nasional.tempo.co\/read\/news\/2016\/10\/20\/063813906\/media-terseret-dugaan-penyuapan-ini-kata-aji\">Media Terseret Dugaan Penyuapan, Ini Kata AJI<\/a><br \/><br \/>4. Perkuat industri pertahanan dalam negeri, mendorong konsep pertahanan dan keamanan berbasis human security, menolak wacana kembalinya dwi fungsi TNI, ciptakan aparat keamanan yang professional.<br \/><br \/>5. Menciptakan Pendidikan berkualitas dan aplikatif yang dapat diakses oleh seluruh lapisan masyarakat untuk mencerdaskan kehidupan Bangsa, dan mencetak sumber daya manusia indonesia yang berkarakter, dan&nbsp; berdaya saing global.<br \/><br \/>6. Membangun solidaritas nasional guna menghadapi ancaman budaya yang merusak nilai nilai Pancasila.<br \/><br \/>7. Mendorong kebijakan pemerintah yang pro poor untuk menekan kesenjangan ekonomi agar tercipta keadilan sosial dan stabilitas di masyarakat.<br \/><br \/>8. Menolak praktik penegakan hukum yang tebang pilih dan penggunaan hukum sebagai alat kekuasaan, serta menuntut segera diselesaikannya kasus-kasus besar yang jalan ditempat.<br \/><br \/>9. Pengelolaan pemerintahan berbasis good governance dan clean government. Menolak segala bentuk intervensi asing terhadap kedaulatan politik Indonesia.<br \/><br \/><strong>MARIA RITA<\/strong><\/p>",
		"created": "1477011564",
		"author": "",
		"topicId": "0",
		"topicTitle": "",
		"imageUrl": "http:\/\/statik.tempo.co\/?id=549114",
		"imageCaption": "",
		"newsUrl": "http:\/\/tempo.co\/read\/news\/2016\/10\/21\/078813969",
		"newsTinyUrl": "http:\/\/tempo.co\/read\/news\/2016\/10\/21\/078813969",
		"relatedTotal": 0,
		"commentTotal": "0",
		"categoryId": 1
	}
}
```
semuanya authornya selalu kosong

majority sih author itu selalu taro di paling belakang, dan didalam tag `<strong>`
tapi ada beberapa page contohnya: https://metro.tempo.co/read/news/2016/10/05/083809732/perang-pilkada-di-dunia-maya-percakapan-soal-ahok-dominan
yang ga dimasukin kedalam tag `<strong>`, saya gak kepikiran sih selector yang bisa handle both case, karena case ke 2 sangat random, bisa didalam p, atau bahkan ga ada didalam tag apapun.
ada masukan? :smile:

2016-10-26 17:51 UTC, pyk commented
@kevinluvian untuk kasus seperti ini mending kita hindari sih, kalo bikin selector takutnya kita dapet unexpected random value yang bukan author

2016-10-26 17:57 UTC, pyk requested changes
LGTM, tinggal formatting aja biar sama kita pake 4 space ya

2016-10-26 17:59 UTC, pyk commented
@kevinluvian aku udah coba, looks good! palingan tinggal formatting aja ya samain sama yg lain pake 4 space hehe 🙇

2016-10-27 02:50 UTC, kevinluvian commented
oops sorry :sweat:

2016-10-27 09:43 UTC, pyk approved these changes

2016-10-27 09:43 UTC, merged