Search Box Fix and Updates (Closes #66)
pyk/rojak pull request #125
Opened 2016-10-23 07:14 UTC by CodeRiderz

- Split search components
- Enhance container to mantain search state and layout
- Add ResultWrapper as a handler to show result based on keyword
- Use `redux-router` to mantain redux history
- update `react-hot-loader` to `2.0.0-alpha`, so we could use `getter` instead of `bind`

2016-10-23 07:52 UTC, pyk commented
cc: @rromadhoni @adrianha, accept via review ya

2016-10-23 16:37 UTC, adrianha requested changes
Everything looks cool mas!
Tinggal validasi redux devtoolsny aja hehe

2016-10-23 16:37 UTC, adrianha commented on rojak-ui-web/src/store.js
> +  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
Tadi aku coba di tempatku error mas karena ga da extension redux devtools dan validasi ini return nya undefined.
Parameter di dalam compose harus berupa function, jadi bisa diubah seperti ini untuk validasinya...
window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : f => f

2016-10-24 05:08 UTC, CodeRiderz commented
@adrianha Sudah di revisi ya, kelupaan pas pindah pake `redux-router`. Sori2.
Ini apakah root cause dari error yang kamu sebutkan di slack ?

2016-10-24 05:55 UTC, adrianha commented
iya @CodeRiderz, itu root cause dari yang kemarin aku kirim di slack.
ok sudah solved errornya...

2016-10-24 06:00 UTC, adrianha approved these changes

2016-10-24 07:39 UTC, pyk approved these changes

2016-10-24 07:39 UTC, merged