Feature/kompascom scrapper
pyk/rojak pull request #63
Opened 2016-10-12 18:27 UTC by imrenagi

* Add scrapper for kompas.com and handle its pagination.
* The last time of scrapping is successfully stored on database, but the operations for saving the scrapped news to database cant be invoked. dont understand why.
* The default user agent used in the scrappy cant be used to scrap kompas.com. I need to figure it out how to change the user_agent for kompas.com

2016-10-12 23:01 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +UPDATE `media` SET last_scraped_at=%s WHERE name=%s;
Kita langsung pake 

```sql
UPDATE `media` SET last_scraped_at=UTC_TIMESTAMP() WHERE name=%s;
```
aja mas

2016-10-12 23:01 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +
Untuk overwrite global setting kita bisa pake ini mas https://doc.scrapy.org/en/latest/topics/settings.html

2016-10-12 23:01 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +                self.cursor.execute(sql_update_media, [datetime.now(), self.name])
Karena kita udah pake `UTC_TIMESTAMP()` jadi kita gak perlu pake `datetime.now()` mas

2016-10-12 23:07 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +UPDATE `media` SET last_scraped_at=%s WHERE name=%s;
oke bay

2016-10-12 23:07 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +
Oke.

2016-10-12 23:07 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +                self.cursor.execute(sql_update_media, [datetime.now(), self.name])
oke.

2016-10-12 23:07 UTC, imrenagi commented
Untuk masalah nyimpen ke database ada ide gak @pyk ?

2016-10-12 23:09 UTC, pyk commented
Kalau di aku dia error gara2 UA masihan mas:

```
(rojak) % scrapy crawl kompascom
2016-10-13 05:57:46 [scrapy] INFO: Scrapy 1.2.0 started (bot: rojak_pantau)
2016-10-13 05:57:46 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'rojak_pantau.spiders', 'SPIDER_MODULES': ['rojak_pantau.spiders'], 'ROBOTSTXT_OBEY': True, 'USER_AGENT': 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1', 'BOT_NAME': 'rojak_pantau'}
2016-10-13 05:57:46 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-10-13 05:57:46 [kompascom] INFO: Fetching media information
Unhandled error in Deferred:
2016-10-13 05:57:46 [twisted] CRITICAL: Unhandled error in Deferred:


Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 163, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/home/vagrant/rojak/rojak-pantau/rojak_pantau/spiders/kompascom.py", line 67, in from_crawler
    *args, **kwargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/home/vagrant/rojak/rojak-pantau/rojak_pantau/spiders/kompascom.py", line 49, in __init__
    self.media['id'] = row[0]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
2016-10-13 05:57:46 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/home/vagrant/rojak/rojak-pantau/rojak_pantau/spiders/kompascom.py", line 67, in from_crawler
    *args, **kwargs)
  File "/home/vagrant/.virtualenvs/rojak/local/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/home/vagrant/rojak/rojak-pantau/rojak_pantau/spiders/kompascom.py", line 49, in __init__
    self.media['id'] = row[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Kalau news itemnya udah ke pipeline seharusnya udah bisa sih

2016-10-12 23:11 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +    name = "kompascom"
Hoo kita pake `kompas` mas (sesuai nama di webnya)

2016-10-12 23:11 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +    name = "kompascom"
oke gw ganti. gw ngikutin yg detik sih. sip

2016-10-12 23:11 UTC, pyk commented
oh wait itu error yg di atas gara2 namanya `kompascom` seharusnya `kompas`

2016-10-12 23:12 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +    name = "kompascom"
https://github.com/pyk/rojak/blob/master/rojak-database/data_media.json#L12

2016-10-12 23:20 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +    name = "kompascom"
udah diupdate bay.

2016-10-12 23:21 UTC, girikuncoro requested changes

2016-10-12 23:21 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +        month = _.translate("idn")[info_date[1]];
usage i18n tinggal cukup `_` aja:
```
month = _.translate("idn")[info_date[1]];
```
jadi:
```
month = _(info_date[1])
```
soalnya udah ada di `__init__.py` nya si `i18n` [ini](https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/i18n/__init__.py#L3).

ohya sama semua semicolonnya diilangin, soalnya ini python :P 

@pyk gw berencana nambahin pep8 linter boleh gak :D https://pypi.python.org/pypi/flake8

2016-10-12 23:21 UTC, girikuncoro commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +        return datetime.strptime(formatted_date, '%d %B %Y, %H:%M');
jangan lupa diconvert ke UTC pake `wib_to_utc`, ini masih WIB

2016-10-12 23:46 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +        month = _.translate("idn")[info_date[1]];
hahaha bisa ya sintax di python kayak gitu. siap. diedit dulu mas

2016-10-12 23:48 UTC, imrenagi commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +        return datetime.strptime(formatted_date, '%d %B %Y, %H:%M');
updated.

2016-10-13 03:01 UTC, pyk approved these changes
Oke LGTM! :ok_hand:

2016-10-13 03:03 UTC, pyk commented on rojak-pantau/rojak_pantau/spiders/kompascom.py
> +        month = _.translate("idn")[info_date[1]];
@imrenagi @girikuncoro btw menurutku lebih jelas `_.translate("idn")[info_date[1]];` sih mas haha

Boleh boleh mas :+1:

2016-10-13 03:09 UTC, merged