[rojak-pantau] Fail-safe untuk SindoNews
pyk/rojak pull request #84
Opened 2016-10-13 19:24 UTC by kevinluvian

merge for #81

2016-10-14 08:09 UTC, pyk commented
mas sorry2 kemaren lupa bilang kalau sekalian di refactor aja dengan `BaseSpider` untuk yg ini biar sama seperti yg lain 🙇

2016-10-14 08:12 UTC, kevinluvian commented
woops ok

2016-10-14 08:14 UTC, pyk requested changes
We need to use `BaseSpider`

2016-10-16 04:25 UTC, kevinluvian commented
maaf baru sempat, tolong di review @pyk

2016-10-16 05:23 UTC, pyk commented
sep sep aku coba dulu ya mas 🙇

2016-10-16 05:25 UTC, pyk approved these changes

2016-10-16 05:25 UTC, merged